# Generated by Django 6.0.1 on 2026-02-01 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('usd_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='USD rate')),
                ('eur_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='EUR rate')),
                ('is_official', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'usd_rate', 'eur_rate'), name='unique_daily_rate')],
            },
        ),
    ]
