# Generated by Django 6.0.1 on 2026-02-01 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto total')),
                ('category', models.CharField(choices=[('comida', 'Comida'), ('ocio', 'Ocio'), ('transporte', 'Transporte'), ('salud', 'Salud'), ('educacion', 'Educación'), ('hogar', 'Hogar'), ('ropa', 'Ropa'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Artículos')),
                ('type', models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('VES', 'Bolívares')], default='VES', max_length=10, verbose_name='Divisa')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Personalizado')),
                ('exchange_custom_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Tasa de cambio personalizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exchangerate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
