# Generated by Django 6.0.1 on 2026-02-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('VES', 'Bolívares')], default='VES', max_length=10, verbose_name='Divisa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('ajuste', 'Ajuste'), ('factura', 'Factura'), ('pago', 'Pago')], default='factura', max_length=50, verbose_name='Tipo'),
        ),
    ]
